### ISSUE TITLE
this problem about the pip  pip install gTTS playsound

### ISSUE THREAD

**Issue by Ganidu123** [arviz-devs/arviz_dashboard#50]
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\Windows\system32>  pip install gTTS playsound
Requirement already satisfied: gTTS in c:\users\ganidu nimsara\appdata\local\programs\python\python313\lib\site-packages (2.5.3)
Collecting playsound
  Using cached playsound-1.3.0.tar.gz (7.7 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [31 lines of output]
      Traceback (most recent call last):
        File "C:\Users\Ganidu Nimsara\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "C:\Users\Ganidu Nimsara\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Ganidu Nimsara\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\Ganidu Nimsara\AppData\Local\Temp\pip-build-env-iwsrko34\overlay\Lib\site-packages\setuptools\build_meta.py", line 333, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Ganidu Nimsara\AppData\Local\Temp\pip-build-env-iwsrko34\overlay\Lib\site-packages\setuptools\build_meta.py", line 303, in _get_build_requires
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "C:\Users\Ganidu Nimsara\AppData\Local\Temp\pip-build-env-iwsrko34\overlay\Lib\site-packages\setuptools\build_meta.py", line 521, in run_setup
          super().run_setup(setup_script=setup_script)
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Ganidu Nimsara\AppData\Local\Temp\pip-build-env-iwsrko34\overlay\Lib\site-packages\setuptools\build_meta.py", line 319, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 6, in <module>
        File "C:\Users\Ganidu Nimsara\AppData\Local\Programs\Python\Python313\Lib\inspect.py", line 1256, in getsource
          lines, lnum = getsourcelines(object)
                        ~~~~~~~~~~~~~~^^^^^^^^
        File "C:\Users\Ganidu Nimsara\AppData\Local\Programs\Python\Python313\Lib\inspect.py", line 1238, in getsourcelines
          lines, lnum = findsource(object)
                        ~~~~~~~~~~^^^^^^^^
        File "C:\Users\Ganidu Nimsara\AppData\Local\Programs\Python\Python313\Lib\inspect.py", line 1078, in findsource
          raise OSError('could not get source code')
      OSError: could not get source code
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
PS C:\Windows\system32>  

_**this is pwershell error cde.  how to fix it please help me**_

**Comment by OriolAbril** [comment]
Hi @Ganidu123, this looks like an installation error with the `playsound` PyPI package which has nothing to do with this repository (and I for example had never even heard about it) so we can't really help. I checked the [playsound PyPI](https://pypi.org/project/playsound/) page, which links to https://github.com/TaylorSMarks/playsound. That is the repo where you should open the issue to get help.
